# Generated by Django 4.2.4 on 2023-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Name')),
                ('trailer', models.CharField(max_length=365, verbose_name='Intro')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('when', models.DateField(verbose_name='Date of post')),
            ],
        ),
    ]
